--- 
title: "Guidelines on Development of National Soil Legacy Data Repository "
author: "Luis Rodríguez-Lado"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
# output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: openscapes/series
description: "A mini bookdown tutorial book on how to make bookdown books."
---

# Introduction {#introduction}

Legacy soil data is regarded as a crucial scientific resource  in assessing ecosystem health and biodiversity as well as in digital soil mapping (DSM) in studies. Historical soil data helps identify soil quality trends, guiding environmental cleanup and rehabilitation efforts. However, the use of this data faces challenges due to its inherent heterogeneity. This data is often fragmented, decentralised, in different formats, both paper or digital, and  without any kind of harmonisation and quality assessment. This variability in legacy databases arises from multiple factors: the specific goals set for sampling campaigns, the level of precision in measurements and reported data, variations in the depth distribution and the maximum depth of soil samples, the geographical extent of the sampling, and the methodology employed in the sampling design, (Arrouays et al., 2017, and Dobos et al., 2010, Schillaci, 2019). This diversity in the data underscores the complexity and challenges in utilising legacy soil data effectively.
 
A national soil legacy data repository is a storage space to deposit data sets associated with legacy soil data. It serves as a critical tool in both environmental and agricultural planning. It provides the foundational data necessary for informed decision-making, sustainable management practices, and the development of strategies to address current and future challenges in both sectors.

In the realm of environmental planning, the role of a national soil legacy data repository is multifaceted and significant. For climate change adaptation and mitigation, soil data is instrumental in identifying areas with high carbon sequestration potential, thereby guiding efforts to mitigate climate change effects. This data also plays a vital role in assessing the impact of climate change on various ecosystems, helping in predictive analyses. When it comes to biodiversity conservation, soil data is key in pinpointing degraded areas, which is crucial for habitat restoration and conserving biodiversity. Additionally, it provides essential information for the conservation strategies of various flora and fauna, dependent on specific soil conditions.
Historical soil data is invaluable in revealing areas with a history of contamination. This facilitates targeted clean-up and remediation efforts, and also aids in the long-term monitoring of pollution trends and the effectiveness of various pollution control measures. Regarding sustainable land use planning, soil data offers insights crucial for informed decision-making in urban development, including zoning, infrastructure development, and green space allocation. Moreover, understanding soil composition and structure is vital for designing effective erosion and flood control measures, ensuring sustainable and environmentally friendly land use.
In agricultural planning, the use of a national soil legacy data repository is exceptionally valuable and diverse. Soil data plays a crucial role in crop management and planning, particularly in crop suitability analysis, where it helps determine the most suitable crops for specific areas, thereby optimising agricultural output. It also supports precision agriculture practices, enabling the targeted application of fertilisers and water, which enhances efficiency and productivity.
Soil fertility management is another area where soil data proves to be indispensable. Historical data on soil nutrient levels assist in the development of efficient and environmentally friendly fertiliser application strategies. Moreover, the continuous monitoring of soil health, enabled by this data, guides interventions to maintain or improve soil fertility.
In the context of disease and pest management, soil conditions have a notable influence on the prevalence of certain pests and diseases. Historical soil data enables predictive analysis to forecast and manage these challenges effectively. This data also aids in the development of integrated pest management strategies, which are less harmful to the environment and more sustainable in the long term.
Water resource management greatly benefits from soil data as well. Information regarding soil water retention and drainage properties is crucial for efficient irrigation planning and water conservation strategies, which are increasingly important in the face of global water scarcity. Additionally, soil data is instrumental in identifying areas more susceptible to drought, guiding the implementation of drought-resilient agricultural practices.
In risk assessment and management, soil data is necessary in assessing risks such as soil degradation, erosion, and salinization, all of which can significantly impact agricultural productivity. Historical soil data also plays a critical role in the development of climate-resilient farming practices, ensuring sustainable agricultural productivity under the evolving conditions brought about by climate change.
The significance of soil data repositories is clear in the context of digital soil mapping, a field gaining increasing importance in agriculture, environmental management, and climate change mitigation. Data repositories make complex soil information more accessible, simplifying it for a wide range of users, and act as crucial sources of the data necessary for training digital mapping algorithms. This data, encompassing historical and current soil information, is key to calibrating digital soil models, thereby sharpening the accuracy and enhancing the resolution of soil maps.
In this context, soil data repositories play an essential role in predictive modelling addressing key issues such as food security and global environmental changes. They aid in the projection of soil changes under various scenarios like climate change and land use shifts and enabling broad-scale soil assessments at regional and global levels. They assist in identifying risks such as soil erosion and contamination, which are vital for informed and sustainable land management practices. By merging soil data with other environmental datasets, these repositories enable interdisciplinary research, pushing the boundaries in soil science and the methodologies used in digital soil mapping.

[Global Soil Nutrient and Nutrient Budgets maps (GSNmap) Phase I Technical manual] (https://fao-gsp.github.io/GSNmap-TM/) (Harmonize Soil Layer Depths).

[Github](http://github.com). 
----


**Examples:**

We have been using bookdown for the Ocean Health Index:  [**ohi-science.org/data-science-training**](http://ohi-science.org/data-science-training) and Openscapes: [**openscapes.org/series**](https://openscapes.org/series).  
And R Markdown is much more than books and websites -- here's a [**one-minute video about R Markdown**](http://rmarkdown.rstudio.com/lesson-1.html) to get you excited. 

----

## Learn all about Bookdown

The best way to learn more about bookdown is from Yihui Xie himself. You can read his book [bookdown: Authoring Books and Technical Documents with R Markdown](https://bookdown.org/yihui/bookdown/) or watch his webinar [introducing bookdown](https://www.rstudio.com/resources/webinars/introducing-bookdown/).

